qhvejhbawfkbwakhbdfwb

diff --git a/.github/workflows/unity-ci.yml b/.github/workflows/unity-ci.yml
--- a/.github/workflows/unity-ci.yml
+++ b/.github/workflows/unity-ci.yml
@@ -29,22 +29,37 @@ jobs:
         run: |
           echo "Listing Unity directory contents..."
           dir "D:\Hub\2022.3.7f1\Editor"
+
           echo "Listing project directory contents..."
           dir "E:\MyTestingProjects\EasyAR"
-        shell: C:\Windows\system32\cmd.EXE "CALL "{0}""
-          
+
+          echo "Listing build directory contents..."
+          dir "E:\MyTestingProjects\EasyAR\Build\Builds\WindowsBuild"
+
       - name: Build project
         run: |
           echo "Compiling the code..."
           "D:\Hub\2022.3.7f1\Editor\Unity.exe" -quit -batchmode -nographics -projectPath "E:\MyTestingProjects\EasyAR" -buildTarget StandaloneWindows64 -buildPath "E:\MyTestingProjects\EasyAR\Build\Builds\WindowsBuild"
           echo "Compile complete."
-        shell: C:\Windows\system32\cmd.EXE "CALL "{0}""
 
       - name: Set build artifact path
-        run: echo "BUILD_PATH=E:\MyTestingProjects\EasyAR\Build\Builds\WindowsBuild" >> $GITHUB_ENV
+        run: |
+          echo "BUILD_PATH=E:\MyTestingProjects\EasyAR\Build\Builds\WindowsBuild" >> $GITHUB_ENV
+
+      - name: Check upload status
+        run: |
+          if [ ${{ steps.upload-artifact.outputs.result }} == 'success' ]; then
+            echo "Build artifact uploaded successfully."
+          else
+            echo "Failed to upload build artifact."
+            exit 1
+          fi
         
       - name: Upload build
+        id: upload-artifact
         uses: actions/upload-artifact@v2
         with:
           name: build
-          path: ${{ env.buildPath }}
+          path: ${{ env.BUILD_PATH }}
+      
+      
